### ISSUE TITLE
Segfault on "Open ROM"

### ISSUE THREAD

**Issue by vpelletier** [mrexodia/SN8F2288_gui#1]
```cpp
    auto fp = fopen(filename, "rb");
    fseek(fp, 0, SEEK_END);
```
If `filename` is the path of a file which does not exist, `fp` is zero and `fseek` segfaults.

I see the open file dialog code is present, but commented-out. I think implementing it would lower a lot the entry barrier.

**Comment by mrexodia** [comment]
You are right, that was some leftovers I shouldn't have committed :) I fixed the issue and now things seem to work normally... The code is a hot mess, but it has certainly be very helpful for me trying to understand what's going on...
